#!/bin/bash
configJSON=$(jq '.' "$DIR/config.json") # Returns all environment data
defaultIdentity=$(jq -r '.defaultIdentity' <<< "${configJSON}")
sshAgentTime=$(jq -r '.sshAgentTime' <<< "${configJSON}")
environmentsNames=($(jq -r '.environments[].name' <<< "${configJSON}" | tr -d '\r')) # Returns an array of environment names